config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users

  resources :users, only: [:show]
  resources :guests, only: [:create]
  resources :episodes, param: :sharable_link, only: [:create, :show, :destroy]

  get 'test', to: 'welcome#test'

  resources :welcome, only: [:show, :create]

  resources :tracks, only: [:create]

  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  before_save :assign_sharable_link, on: :create
  belongs_to :host, class_name: "User"
  has_many :guests, dependent: :destroy
  has_many :tracks, dependent: :destroy
  validates :name, presence: true

  private
    def assign_sharable_link
      self.sharable_link ||= SecureRandom.hex(4)
    end
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :episode
  validates :name, presence: true

  before_destroy { GuestCleanupJob.perform_later(self) }

  def appear
    AppearanceBroadcastJob.perform_later(self)
  end

end

app/models/track.rb
require 'nokogiri'
class Track < ApplicationRecord
  validates_presence_of :s3_string
  belongs_to :episode

  after_create { TrackBroadcastJob.perform_later(self) }
  
  def download_url
    location
  end

  def name
    key.sub(/.*__(.+)__.*/, '\1')
  end

  private
    def key
      xml_doc.xpath('//Key').text
    end

    def location
      xml_doc.xpath('//Location').text
    end

    def xml_doc
      Nokogiri::XML(s3_string)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :episodes, foreign_key: :host_id
  has_many :tracks, as: :recordable
  validates :name, uniqueness: true

  def host?(episode)
    episode.host_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def assign_guest_cookies(guest)
    cookies.signed['guest_id'] = guest.id
    cookies.signed['is_host'] = guest.is_host
  end

  def after_sign_in_path_for(_resource)
    user_path(current_user)
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  before_action :find_episode, only: [:show]
  before_action :authenticate_user!, only: [:create, :destroy]

  def show
    @guest = Guest.new
    set_s3_direct_post(@episode)
    create_guest_from_current_user if guest_hosts?(@episode)
    if !current_user || !current_user.host?(@episode)
      render(partial: 'episodes/guest_page', layout: false)
    end
  end

  def create
    @episode = current_user.episodes.build(episode_params)
    if @episode.save
      create_guest_from_current_user
      redirect_to episode_path(sharable_link: @episode.sharable_link)
    else
      flash[:alert] = @episode.errors.full_messages.first
      redirect_to user_path(current_user)
    end
  end

  def destroy
    episode = find_episode
    delete_s3_objects(episode)
    episode.destroy
    redirect_to user_path(current_user)
  end

  private
    def guest_hosts?(episode)
      episode.host == current_user && !episode.guest_ids.include?(cookies.signed['guest_id'])
    end

    def create_guest_from_current_user
      guest = @episode.guests.create(name: current_user.name, is_host: true)
      assign_guest_cookies(guest)
    end

    def find_episode
      @episode = Episode.find_by(sharable_link: params[:sharable_link]) 
      @episode ? @episode : not_found
    end

    def set_s3_direct_post(episode)
      @s3_direct_post = S3_BUCKET.presigned_post(
        key: "wavecastr/#{episode.host.name}/episode_#{episode.sharable_link}/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
    end

    def delete_s3_objects(episode)
      prefix = "wavecastr/#{current_user.name}/episode_#{episode.sharable_link}"
      S3_BUCKET.objects(prefix: prefix).each do |obj|
        obj.delete
      end 
    end

    def episode_params
      params.require(:episode).permit(:name, :description, :encoder)
    end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def create
    guest = Guest.new(guest_params)
    if guest.save
      cookies.signed[:guest_id] = guest.id
      render plain: guest.name, :status => :ok
    else
      head 422
    end
  end

  private
    def guest_params
      params.require(:guest).permit(:name, :episode_id)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def create
    episode = Episode.find_by(sharable_link: params['sharable_link'])
    new_track = episode.tracks.build(track_params)
    if new_track.save
      head :ok
    else
      head 422
    end
  end

  private
    def track_params
      params.require('track').permit('s3_string')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @episode = Episode.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def test
    render :test
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def audio_filetypes
    ["mp3", "wav", "ogg"]
  end

  def is_host?(episode)
    user_signed_in? && current_user.host?(episode)
  end

  def unregistered_guest?(episode)
    (!current_user || !current_user.host?(episode)) && !episode.guest_ids.include?(cookies.signed[:guest_id])
  end

end

app/helpers/guests_helper.rb
module GuestsHelper
  def current_guest
    Guest.find_by(id: cookies.signed[:guest_id])
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/episodes/_aws_s3_upload_form.html.erb
<%= form_for(@episode, html: { hidden: true, class: 'directUpload', data: { 
	'form-data' => (@s3_direct_post.fields), 
	'url' => @s3_direct_post.url,
	'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <%= f.file_field :track %>
<% end %>

app/views/episodes/_episode.html.erb
<div class="episode panel panel-default">
  <div class="panel-body">
    <p>
      <h3 class="episode-title"><%= link_to "#{episode.name}", episode_path(sharable_link: episode.sharable_link), class: "episode-title" %></h3>
    </p>
    <p><small><%= episode.created_at %></small></p>
    <p><%= button_to "Delete", episode_path(sharable_link: episode.sharable_link), method: 'delete', class: "btn btn-danger" %></p>
  </div>
</div>

app/views/episodes/_guest_page.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/head' %> 

  <body>
    <div class="header">
      <div class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <img src="/images/Wellen-lineart-800px.png" alt="WaveCastr" height="80">
            <a class="h1" href="/">WaveCastr</a>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div id="flash">
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name unless name == "notice" %>
        <% end %>
      </div>
      <%= render(template: 'episodes/show', layout: false) %>
    </div>
  </body>
</html>

app/views/episodes/modals/_register_guest.html.erb
<!-- Register Guest Modal -->
<div class="modal fade" id="register-guest-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Register</h4>
      </div>
      <div class="modal-body">
        <div id="modal-flash" style="height: 30px"></div>
        <%= form_for @guest do |f| %>
          <%= hidden_field :guest, :episode_id, value: @episode.id %>
          <%= f.text_field :name, placeholder: "Enter your name", class: "form-control input-lg", maxlength: 10 %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="submit" id="register-guest-btn" class="btn btn-primary" form="new_guest">Go</button>
      </div>
    </div>
  </div>
</div>

app/views/episodes/modals/_share_link.html.erb
<!-- Share Link Modal -->
<div class="modal fade" id="share-link-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Share Link</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <input class="form-control input-lg" id="episode-link" value="<%= episode_url(sharable_link: @episode.sharable_link) %>">
        </div>
        <div class="form-group">
          <button id="copy-btn" class="btn btn-primary" data-dismiss="modal" data-clipboard-target="#episode-link">Copy</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  new Clipboard('#copy-btn');
</script>

app/views/episodes/show.html.erb
<!-- ChatBox & Guests -->
<div class="row">
  <div class="col-md-3" id="left-container">
    <% if is_host?(@episode) %>
      <div class="share-button">
        <button id="present-share-link-modal" class="btn btn-block" data-toggle="modal" data-target="#share-link-modal">Share Link</button>
      </div> 
    <% end %>
    <div id="guest-list">
      <%= render @episode.guests.order(is_host: :desc) %>
    </div>
  </div>
  
  <div class="col-md-9" id="right-container">
    <div id="chat-container"></div>
    <div id="input-box">
      <input id="chat-input" class="form-control pull-left" placeholder="Type your message here"/>
      <button id="chat-send" class="pull-right">Send</button>
    </div>
  </div>
</div>
<!-- End ChatBox & Guests -->

<!-- Control Panel -->
<div class="row">
  <div id="control-panel" class="text-right">
    <div id="timer" class="text-lg"></div>
    <div id="record-buttons" <%= 'hidden' unless is_host?(@episode) %> >
      <button id="init" class="btn btn-primary">Activate Mics</button>
      <button id="start" class="btn btn-primary" disabled><span class="glyphicon glyphicon-record"></span> Record</button>
      <button id="stopButton" class="btn btn-primary" disabled><span class="glyphicon glyphicon-stop"></span> Stop</button>
    </div>
  </div>
  <!-- Spinner -->
  <div id="local-recording" class="text-center">
  </div>
</div>

<!-- Track List -->
<% if is_host?(@episode) %>
  <div class="row">
    <div class="col-md-12" id="track-list" <%= 'hidden' if @episode.tracks.empty? %> >
      <h1 class="page-header">Tracks</h1>
        <%= render @episode.tracks %>
    </div>
  </div>
<% end %>

<!-- Modals -->
<% if is_host?(@episode) %>
  <%= render '/episodes/modals/share_link' %>
<% end %>
<% if unregistered_guest?(@episode) %>
  <%= render '/episodes/modals/register_guest' %>
<% end %>

<!-- Encoder -->
<div id="encoder" hidden><%= @episode.encoder %></div>

<!-- Current Guest -->
<div id="current_guest" hidden><%= current_guest.name if current_guest %></div>

<%= render '/episodes/aws_s3_upload_form' %>

<% if unregistered_guest?(@episode) %>
  <script src="/js/registerGuest.js"></script>
<% else %>
  <script>
    initiateActionCable();
    subscribeToAllChannels();
  </script>
<% end %>
<script src="/js/record.js"></script>

app/views/guests/_guest.html.erb
<div id="guest-<%= guest.id %>" class="guest">
  <div>
    <i class="fa fa-user<%= '-circle-o' if guest.is_host %> fa-2x <%= guest.status %>" aria-hidden="true"></i>
    <h3><%= guest.name %></h3>
  </div>
</div>

app/views/layouts/_head.html.erb
<head>
  <title>Wavecastr</title>
  <link href="/images/wavecastr-icon.png" rel="icon">
  <link href="https://fonts.googleapis.com/css?family=Anton|Indie+Flower|Supermercado+One|Titillium+Web" rel="stylesheet">
  <script src="https://use.fontawesome.com/759e55b199.js"></script>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span> 
				</button>
        <img src="/images/Wellen-lineart-800px.png" alt="WaveCastr" height="80">
        <a class="h1" href="/">WaveCastr</a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-menu">
        <ul class="nav navbar-right nav-pills">
          <% if user_signed_in? %>
            <li><%= link_to current_user.name, user_path(current_user), class: 'nav-btn text-gold' %></li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'nav-btn text-gold') %>
            </li>
          <% else %>
            <li>
              <%= link_to('Register', new_user_registration_path, class: 'text-gold') %>
            </li>
            <li>
            <%= link_to('Login', new_user_session_path, class: 'text-gold') %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/head' %>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div id="flash">
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name unless name == "notice" %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tracks/_track.html.erb
<div  class="track">
  <h4><%= link_to track.name, track.download_url %></h4>
</div>

app/views/users/_host.html.erb
<div id="host" class="guest">
  <div>
    <i class="fa fa-user-circle-o fa-2x" aria-hidden="true"></i>
    <h3 <%= 'id=current_user' if user_signed_in? && current_user.host?(@episode) %>><%= host.name %></h3>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already a user? Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <div id="new-episode-div">
    <button id="present-new-episode-modal" class="btn btn-primary btn-block" data-toggle="modal" data-target="#new-episode-modal">
      New Episode
    </button>
  </div>
</div>

<div class="row">
  <div id="episode-list">
    <%= render current_user.episodes.order(created_at: :desc) %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="new-episode-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">New Episode</h4>
      </div>
      <div class="modal-body">
        <%= form_for @episode do |f| %>
          <%= f.text_field :name, placeholder: "Episode name", class: "form-control input-lg", autofocus: true %>
          <%= f.radio_button :encoder, 'mp3', :checked => true %>
          <%= f.label :encoder, 'mp3', :value => 'mp3', :class => 'encoding' %>
          <%= f.radio_button :encoder, 'wav' %>
          <%= f.label :encoder, 'wav', :value => 'wav', :class => 'encoding' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="submit" id="new-episode-modal-btn" class="btn btn-primary" form="new_episode">Go</button>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="tag-line" class="row">
  <div class="col-md-12">
    <h1 id="over-line-header" class="text-white page-header">Recording podcasts is difficult.</h1>
    <h1 id="under-line-header" class="text-white text-right">WaveCastr makes it easy.</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="get-started-button">
    <%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-lg btn-block" %>
  </div>
</div>

<div class="row">
  <div id="blurbs">
    <div class="blurb col-md-4 text-white">
      <i class="fa fa-3x fa-podcast text-gold" aria-hidden="true"></i>
      <h3>Record Locally</h3>
      <p class="h4">Avoid VoIP compression and internet connection issues by recording in the browser.</p>
    </div>
    <div class="blurb col-md-4 text-white">
      <i class="fa fa-3x fa-file-audio-o text-gold" aria-hidden="true"></i>
      <h3>Separate Tracks</h3>
      <p class="h4">Each user's audio is stored in a separate file to make post-production a snap.</p>
    </div>
    <div class="blurb col-md-4 text-white">
      <i class="fa fa-3x fa-mixcloud text-gold" aria-hidden="true"></i>
      <h3>Cloud Storage</h3>
      <p class="h4">Your files are securely stored in Amazon's S3 cloud storage platform allowing for fast retrieval.</p>
    </div>
  </div>
</div>